# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 류아영(RAY)
title: 안정속의 변화를 추구하는 개발자
email: ayryu2005@gmail.com
# email_title: Email (Email title override)
phone: 010-4065-3136
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  RyuAY

about_profile_image: "./assets/profile.jpg"
about_content: | 
  "한샘과의 외주 계약을 통해 한샘 내 프로그램의 개발, 운영, 유지보수를 담당하며 안정적인 시스템 운영과 서비스 품질 향상을 위해 노력해왔습니다 또한 회사 내 다양한 프로젝트에도 참여하며 요구사항에 맞는 효율적인 백엔드 구현 경험을 쌓았습니다.
  
  새로운 기술 스택이나 업무 환경에도 빠르게 적응하며, 이를 통해 변경되는 요구사항과 프로젝트 환경 속에서도 시스템의 안정성과 성능을 유지하고 지속적으로 개선 가능한 구조를 구현하고자 합니다.
  
  다양한 직무의 구성원들과 함께 협업하며 커뮤니케이션 하는 과정을 좋아합니다. 개발 과정에서 발생하는 문제를 팀과 공유하며 함께 해결해 나가는 것을 우선시하고, 개인의 성과와 더불어 팀 전체의 효율과 완성도를 높이는 데 주력합니다.
  
  오류나 실수의 원인을 파악하고 개선하여 반복되지 않도록 관리하는 것을 중요하게 생각합니다. 앞으로도 안정성과 확장성을 갖춘 백엔드 시스템을 구축하며, 신뢰받는 개발자로 성장하고자 합니다.

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: (주)한영DS
        sub_title: 대리 / Full stack Engineer
        caption: 2021.01 ~ 현재
        link: 한샘 외주 프로그램 담당(AS)
        quote: >
          한샘서비스센터 개편
        description: | 
          - Spring 기반으로 일부 기존 JS 기반 클라이언트 처리 로직을 서버 단으로 이전하여 데이터 검증과 로직 실행을 수행함으로써 이를 통해 외부 조작 가능성을 차단하고 안정적인 시스템 운영 환경 마련

          - 접수 프로세스 변경으로 자가조치 유도 및 셀프 AS접수를 증가시켜 고객센터를 통한 AS접수건을 감소시킴으로서 고객센터 운영 효과성 확보

          - BackEnd, FrontEnd, Web Design 경험을 토대로 담당자와 디자이너 부재 상황에도 빠른 피드백 및 대처
      - layout: left
        quote: >
          업무 진행 상황판 개선
        description: | 
          - 미사용 기능 삭제, 정보 추가, 산출 방식 변경 등으로 AS프로, 센터장, AS스탭 등 작업 인원의 업무효율을 약 186시간 / 월 개선

          - 기존 조회 기준 외 신규 단위 조회 프로세스 추가로 방식을 세분화하여 사용자의 업무 편의성 증대

          - MSSQL SP 구조를 개선해 배치 처리로 인한 데이터 지연을 해소하고 실시간 조회 기능 구현으로 업무 효율성 향상
      - layout: left
        quote: >
          담당자 변경 프로세스 개선
        description: | 
          - 기존 상위 단위 기준으로만 가능하던 담당자 변경 기능을 품목 단위로 개선하여, 담당자 간 불필요한 확인 및 소통 과정을 줄이고 효율성 향상
      - layout: left
        title: ENEREVER
        sub_title: 대리 / BackEnd Engineer
        caption: 2024.06 ~ 2025.06
        link: 배터리 솔루션
        quote: >
          시스템 내 바코드, 메일 기능 개발
        description: | 
          - Spring Boot 기반으로 JPA와 QueryDSL을 사용해 MES 시스템 내 바코드 생성, 출력 및 이메일 발송 기능 개발

          - 메인 및 그리드 메뉴 구성 디자인 및 CSS 관리로 전체적인 프로젝트 통일성 유지
      - layout: left
        title: SMarina
        sub_title: 사원 / Full stack Engineer
        caption: 2023.01 ~ 2023.05
        link: 항만 관리 시스템
        quote: >
          신규 홈페이지 제작
        description: | 
          - Node.js 기반으로 React를 사용하여 기업 소개 홈페이지 신규 제작
  - title: Skill
    layout: list
    quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
    content:
      - layout: left
        title: Languages
        description: | 
          - Java
          - JavaScript, TypeScript 
          - HTML, CSS
      - layout: left
        title: Frameworks & Libraries
        description: | 
          - Java EE (Jakarta EE), Spring, Spring Boot
          - QueryDSL
          - React
      - layout: left
        title: Infrastructure & Databases
        description: | 
         - Nginx, Tomcat, JBoss (WildFly)  
         - Linux  
         - MySQL, MSSQL
      - layout: left
        title: Tools & IDEs
        description: | 
          - Git, GitHub, Bitbucket  
          - Jenkins, Jira  
          - Eclipse, IntelliJ, VS Code
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
